### PR TITLE
Adding AMAI22 paper

### PR DESCRIPTION
**Pull request by giuseppeperelli**

### CODE REVIEW

**Review by francescofuggitti — CHANGES_REQUESTED** [review]
Could you please resolve conflicts before merging? I guess your local version needs to be updated.

**Comment by giuseppeperelli** [comment]
Take a look now, I think I fixed it. Thanks!

**Comment by francescofuggitti** [comment]
Are you sure the item

> @article{arxiv2022dfpz,
  author    = {Giuseppe {De Giacomo} and
               Dror Fried and
               Fabio Patrizi and
               Shufang Zhu},
  title     = {Mimicking Behaviors in Separated Domains},
  journal   = {CoRR},
  volume    = {abs/2205.09201},
  year      = {2022},
  url_paper = {https://whitemech.github.io/papers/2022/arxiv2022dfpz.pdf},

has to be removed? I can still see it on the master

**Comment by giuseppeperelli** [comment]
Hi Francesco,
I should have fixed it correctly now.

**Review by francescofuggitti — APPROVED** [review]

**Pull request merged**
